
version: '2'
services:
  api:
    build:
      context: .
      dockerfile: ./img-rest/Dockerfile
    image: img-rest
    container_name: img-rest
    ports:
      - 80:5000
    volumes:
      - ./img-store:/img-store
    environment:
      - APP_ENV=DockerProduction
    links:
      - engine
  engine:
    build:
      context: .
      dockerfile: ./img-engine/Dockerfile
    image: img-engine
    container_name: img-engine
    ports:
      - 5555:5555
    volumes:
      - ./img-store:/img-store
    environment:
      - APP_ENV=DockerProduction

