
version: '2'
services:
  web:
    build:
      context: ./
      dockerfile: ./img-rest/Dockerfile
    image: img-rest
    container_name: img-rest
    ports:
      - 80:5000
    volumes:
      - ./img-store:/img-store
    environment:
      - APP_ENV=DockerProduction

